// Generated by scripts/build_public_api_contracts.py; do not edit.
export interface FeaturePagePayload {
  readonly filters: Readonly<Record<string, unknown>>;
  readonly generated_at_utc: string | null;
  readonly has_more: boolean;
  readonly limit: number;
  readonly matching_total: number;
  readonly offset: number;
  readonly production_control_possible: false;
  readonly read_only: true;
  readonly reset_required: boolean;
  readonly revision: string;
  readonly rows: ReadonlyArray<Readonly<Record<string, unknown>>>;
  readonly schema_version: 1;
  readonly summary: Readonly<Record<string, unknown>>;
}
