"""Selective local payload cache for ephemeral packed-store consumers.

Heads, manifests, and inventories remain synchronized. Large blob and ZIP pack
objects may be removed from an ephemeral node only after a durable peer has a
complete valid folder. Negated Syncthing ignore rules can temporarily hydrate
the exact objects needed by one release.
"""

from __future__ import annotations

import json
import os
import stat
import time
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Mapping

from stockagent.data_sync.desync_snapshots import (
    SnapshotError,
    _path_under,
    _utc_iso_from_ns,
    atomic_write_bytes,
    atomic_write_json,
    sha256_file,
)
from stockagent.data_sync.packed_snapshots import ResolvedSnapshot


EDGE_CACHE_SCHEMA_VERSION = 1
EDGE_IGNORE_NAME = ".stignore-edge"
EDGE_INCLUDE_DIRECTIVE = f"#include {EDGE_IGNORE_NAME}"
EDGE_LOCAL_IGNORE = f"(?d){EDGE_IGNORE_NAME}"
EDGE_PAYLOAD_PREFIXES = ("objects/blobs", "objects/packs")


def release_payload_relpaths(resolved: ResolvedSnapshot) -> set[str]:
    """Return blob/pack paths needed to reconstruct one resolved release."""

    result: set[str] = set()
    for raw in resolved.manifest["archive"]["objects"]:
        relpath = PurePosixPath(str(raw["relpath"]))
        if not any(
            relpath == PurePosixPath(prefix)
            or PurePosixPath(prefix) in relpath.parents
            for prefix in EDGE_PAYLOAD_PREFIXES
        ):
            raise SnapshotError(f"release payload has an unsupported path: {relpath}")
        result.add(relpath.as_posix())
    return result


def render_edge_ignore(allowed_relpaths: Iterable[str] = ()) -> bytes:
    """Render first-match Syncthing rules for an index-only replica."""

    allowed: list[str] = []
    for raw in sorted(set(allowed_relpaths)):
        relpath = PurePosixPath(raw)
        if relpath.is_absolute() or ".." in relpath.parts:
            raise SnapshotError(f"unsafe edge-cache object path: {raw}")
        if not any(
            relpath == PurePosixPath(prefix)
            or PurePosixPath(prefix) in relpath.parents
            for prefix in EDGE_PAYLOAD_PREFIXES
        ):
            raise SnapshotError(f"edge-cache allow path is not a payload object: {raw}")
        allowed.append(relpath.as_posix())
    lines = [
        "// Generated by manage_packed_edge.py; first matching pattern wins.",
        "// Exact exceptions precede the general index-only exclusions.",
        *(f"!/{path}" for path in allowed),
        "/objects/blobs/**",
        "/objects/packs/**",
        "",
    ]
    return "\n".join(lines).encode("utf-8")


def ensure_edge_include(sync_root: Path) -> None:
    """Preserve existing ignore rules while adding the local edge include."""

    sync_root = sync_root.resolve()
    path = sync_root / ".stignore"
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        text = ""
    lines = text.splitlines()
    changed = False
    if EDGE_LOCAL_IGNORE not in lines:
        lines.append(EDGE_LOCAL_IGNORE)
        changed = True
    if EDGE_INCLUDE_DIRECTIVE not in lines:
        lines.append(EDGE_INCLUDE_DIRECTIVE)
        changed = True
    if changed:
        payload = "\n".join(lines).rstrip() + "\n"
        atomic_write_bytes(path, payload.encode("utf-8"))


def write_edge_ignore(sync_root: Path, allowed_relpaths: Iterable[str] = ()) -> Path:
    sync_root = sync_root.resolve()
    ensure_edge_include(sync_root)
    path = sync_root / EDGE_IGNORE_NAME
    atomic_write_bytes(path, render_edge_ignore(allowed_relpaths))
    return path


def iter_local_payloads(sync_root: Path) -> list[Path]:
    """List only ordinary blob/pack object files under the exact sync root."""

    sync_root = sync_root.resolve()
    result: list[Path] = []
    for prefix in EDGE_PAYLOAD_PREFIXES:
        parent = sync_root.joinpath(*PurePosixPath(prefix).parts)
        if not parent.exists():
            continue
        if not parent.is_dir() or parent.is_symlink():
            raise SnapshotError(f"edge payload root is not a real directory: {parent}")
        for path in sorted(parent.glob("*/*")):
            info = path.stat(follow_symlinks=False)
            if not stat.S_ISREG(info.st_mode):
                raise SnapshotError(f"edge payload is not a regular file: {path}")
            result.append(path)
    return result


def local_payload_inventory(sync_root: Path) -> dict[str, Any]:
    sync_root = sync_root.resolve()
    files = iter_local_payloads(sync_root)
    return {
        "files": len(files),
        "bytes": sum(path.stat(follow_symlinks=False).st_size for path in files),
        "allocated_bytes": sum(
            path.stat(follow_symlinks=False).st_blocks * 512 for path in files
        ),
    }


def verify_payload_relpaths(
    sync_root: Path, relpaths: Iterable[str]
) -> dict[str, Any]:
    """Hash exact hydrated payloads and reject path/digest mismatches."""

    sync_root = sync_root.resolve()
    files = 0
    verified_bytes = 0
    for raw in sorted(set(relpaths)):
        path = _path_under(sync_root, raw, "edge payload relpath")
        expected = path.name.split(".", 1)[0]
        if sha256_file(path) != expected:
            raise SnapshotError(f"edge payload checksum mismatch: {path}")
        files += 1
        verified_bytes += path.stat().st_size
    return {"files": files, "verified_bytes": verified_bytes}


def prune_local_payloads(
    sync_root: Path,
    *,
    allowed_relpaths: Iterable[str] = (),
    apply: bool = False,
) -> dict[str, Any]:
    """Remove ignored local payload copies, retaining metadata and exceptions."""

    sync_root = sync_root.resolve()
    allowed = set(allowed_relpaths)
    deleted_files = deleted_bytes = deleted_allocated_bytes = 0
    would_delete_files = would_delete_bytes = would_delete_allocated_bytes = 0
    for path in iter_local_payloads(sync_root):
        relative = path.relative_to(sync_root).as_posix()
        if relative in allowed:
            continue
        before = path.stat(follow_symlinks=False)
        would_delete_files += 1
        would_delete_bytes += before.st_size
        would_delete_allocated_bytes += before.st_blocks * 512
        if not apply:
            continue
        current = path.stat(follow_symlinks=False)
        if (
            current.st_dev,
            current.st_ino,
            current.st_size,
            current.st_mtime_ns,
        ) != (
            before.st_dev,
            before.st_ino,
            before.st_size,
            before.st_mtime_ns,
        ):
            raise SnapshotError(f"edge payload changed before unlink: {path}")
        path.unlink()
        deleted_files += 1
        deleted_bytes += before.st_size
        deleted_allocated_bytes += before.st_blocks * 512
    return {
        "apply": apply,
        "would_delete_files": would_delete_files,
        "would_delete_bytes": would_delete_bytes,
        "would_delete_allocated_bytes": would_delete_allocated_bytes,
        "deleted_files": deleted_files,
        "deleted_bytes": deleted_bytes,
        "deleted_allocated_bytes": deleted_allocated_bytes,
    }


def write_edge_receipt(
    receipt_root: Path, payload: Mapping[str, Any], *, now_ns: int | None = None
) -> Path:
    current_ns = time.time_ns() if now_ns is None else int(now_ns)
    receipt_root = receipt_root.resolve()
    receipt_root.mkdir(parents=True, exist_ok=True)
    path = receipt_root / f"packed-edge-{current_ns}.json"
    atomic_write_json(
        path,
        {
            "schema_version": EDGE_CACHE_SCHEMA_VERSION,
            "recorded_at": _utc_iso_from_ns(current_ns),
            **dict(payload),
        },
    )
    return path
