#!/usr/bin/env python3
"""Generate the existing feature-page JSON schema and TypeScript envelope."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from stockagent.live.data_monitor_api_contract import feature_page_schema  # noqa: E402


def _typescript(value: dict) -> str:
    if "const" in value:
        return json.dumps(value["const"])
    if "enum" in value:
        return " | ".join(json.dumps(item) for item in value["enum"])
    if "anyOf" in value:
        return " | ".join(_typescript(item) for item in value["anyOf"])
    kind = value.get("type")
    if kind == "array":
        return f"ReadonlyArray<{_typescript(value.get('items', {}))}>"
    if kind == "object":
        return "Readonly<Record<string, unknown>>"
    return {"integer": "number", "number": "number", "string": "string",
            "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = feature_page_schema()
    body = schema["$defs"]["FeaturePagePayload"]
    typescript = "// Generated by scripts/build_public_api_contracts.py; do not edit.\n"
    typescript += "export interface FeaturePagePayload {\n"
    for name, item in body["properties"].items():
        optional = "" if name in body["required"] else "?"
        typescript += f"  readonly {name}{optional}: {_typescript(item)};\n"
    typescript += "}\n"
    properties = body['properties']
    constraints = {name: properties[name][name2] for name,name2 in (
        ('schema_version','enum'), ('read_only','const'), ('production_control_possible','const'))}
    for name in ('offset','limit','matching_total'):
        constraints[name] = {key:properties[name][key] for key in ('minimum','maximum')}
    constraints['revision_pattern'] = properties['revision']['pattern']
    javascript = '// Generated by scripts/build_public_api_contracts.py; do not edit.\n'
    javascript += 'globalThis.StockAgentFeaturePageConstraints = Object.freeze('+json.dumps(constraints,indent=2)+');\n'
    targets = {
        ROOT / "schemas/public/data-monitor-feature-page-v1.json": json.dumps(schema, indent=2)+"\n",
        ROOT / "services/public_dashboards/api-contracts.d.ts": typescript,
        ROOT / "services/public_dashboards/feature-page-constraints.js": javascript,
    }
    for path, text in targets.items():
        if args.check:
            if not path.is_file() or path.read_text() != text:
                raise ValueError(f"API contract drift: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    print("feature-page contracts verified" if args.check else "feature-page contracts generated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
