#!/usr/bin/env python3
"""Verify the clock used by Taiwan market schedules and repair bounded WSL drift.

``timedatectl`` reports whether a synchronization service is enabled, not
whether chronyd currently has a usable source.  On WSL the Windows host is the
clock authority, so compare both clocks directly.  On native Linux require a
selected chrony source.  Every run writes an atomic receipt; a large offset is
never stepped automatically.
"""

from __future__ import annotations

import argparse
from datetime import datetime
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import time
from typing import Any, Callable
import uuid
from zoneinfo import ZoneInfo


REPO_ROOT = Path(__file__).resolve().parents[1]
TAIPEI = ZoneInfo("Asia/Taipei")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--receipt",
        type=Path,
        default=Path("artifacts/operations/time_sync/latest.json"),
    )
    parser.add_argument("--repair", action="store_true")
    parser.add_argument("--max-offset-ms", type=float, default=500.0)
    parser.add_argument("--max-repair-offset-seconds", type=float, default=300.0)
    parser.add_argument("--samples", type=int, default=3)
    return parser.parse_args()


def _repo_path(path: Path) -> Path:
    return path if path.is_absolute() else REPO_ROOT / path


def _atomic_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + f".tmp.{uuid.uuid4().hex}")
    try:
        with temporary.open("w", encoding="utf-8") as handle:
            json.dump(payload, handle, ensure_ascii=False, indent=2, sort_keys=True)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def _prune_managed_runs(
    directory: Path, *, max_files: int = 2048, max_age_days: int = 365
) -> None:
    """Bound only receipts generated by this checker."""

    try:
        rows = sorted(
            (path for path in directory.glob("*.json") if path.is_file()),
            key=lambda path: path.stat().st_mtime,
            reverse=True,
        )
    except OSError:
        return
    cutoff = time.time() - max_age_days * 86400
    for index, path in enumerate(rows):
        try:
            if index >= max_files or path.stat().st_mtime < cutoff:
                path.unlink(missing_ok=True)
        except OSError:
            continue


def _is_wsl() -> bool:
    try:
        release = Path("/proc/sys/kernel/osrelease").read_text(encoding="utf-8")
    except OSError:
        return False
    return "microsoft" in release.casefold()


def _powershell_path() -> str | None:
    discovered = shutil.which("powershell.exe")
    if discovered:
        return discovered
    candidate = Path(
        "/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
    )
    return str(candidate) if candidate.is_file() else None


def _sample_windows_host_offset(
    *,
    samples: int,
    runner: Callable[..., subprocess.CompletedProcess[str]] = subprocess.run,
) -> dict[str, Any]:
    executable = _powershell_path()
    if not executable:
        raise RuntimeError("powershell.exe is unavailable")
    rows: list[dict[str, float]] = []
    for _ in range(max(1, int(samples))):
        before = time.time()
        completed = runner(
            [
                executable,
                "-NoProfile",
                "-NonInteractive",
                "-Command",
                "[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()",
            ],
            check=True,
            capture_output=True,
            text=True,
            timeout=5,
        )
        after = time.time()
        host_seconds = float(completed.stdout.strip().splitlines()[-1]) / 1000.0
        rows.append(
            {
                "offset_seconds": host_seconds - ((before + after) / 2.0),
                "round_trip_seconds": after - before,
            }
        )
    best = min(rows, key=lambda row: row["round_trip_seconds"])
    return {
        "source": "wsl_windows_host_clock",
        "offset_seconds": best["offset_seconds"],
        "round_trip_seconds": best["round_trip_seconds"],
        "sample_count": len(rows),
    }


def _chrony_tracking(
    *,
    runner: Callable[..., subprocess.CompletedProcess[str]] = subprocess.run,
) -> dict[str, Any]:
    completed = runner(
        ["chronyc", "-c", "tracking"],
        check=True,
        capture_output=True,
        text=True,
        timeout=5,
    )
    fields = completed.stdout.strip().split(",")
    if len(fields) < 14:
        raise RuntimeError("chronyc tracking returned an incomplete row")
    return {
        "source": "chrony_selected_source",
        "reference_id": fields[0],
        "reference_name": fields[1],
        "stratum": int(fields[2]),
        "system_offset_seconds": float(fields[4]),
        "last_offset_seconds": float(fields[5]),
        "rms_offset_seconds": float(fields[6]),
        "root_delay_seconds": float(fields[10]),
        "root_dispersion_seconds": float(fields[11]),
        "leap_status": fields[13],
    }


def _attempt_chrony_repair() -> dict[str, Any]:
    attempts: list[dict[str, Any]] = []
    for command, timeout in (
        (["chronyc", "online"], 5),
        (["chronyc", "burst", "4/8"], 5),
        (["chronyc", "waitsync", "10", "0.5", "0", "1"], 15),
        (["chronyc", "makestep"], 5),
    ):
        completed = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        attempts.append(
            {
                "command": command,
                "returncode": int(completed.returncode),
                "stdout": completed.stdout[-500:],
                "stderr": completed.stderr[-500:],
            }
        )
        if command[1] == "waitsync" and completed.returncode != 0:
            break
    return {"attempts": attempts}


def evaluate_time_sync(
    *,
    repair: bool,
    max_offset_ms: float,
    max_repair_offset_seconds: float,
    samples: int,
) -> dict[str, Any]:
    started = datetime.now(TAIPEI)
    failures: list[str] = []
    repaired = False
    authority: dict[str, Any] = {}
    chrony: dict[str, Any] = {}
    repair_evidence: dict[str, Any] = {}
    try:
        chrony = _chrony_tracking()
    except Exception as exc:
        chrony = {"error": f"{type(exc).__name__}: {exc}"}

    try:
        if _is_wsl():
            authority = _sample_windows_host_offset(samples=samples)
            offset_seconds = float(authority["offset_seconds"])
            if abs(offset_seconds) * 1000.0 > float(max_offset_ms) and repair:
                if abs(offset_seconds) > float(max_repair_offset_seconds):
                    failures.append(
                        "WSL host clock offset exceeds the bounded auto-repair limit"
                    )
                else:
                    time.clock_settime(time.CLOCK_REALTIME, time.time() + offset_seconds)
                    repaired = True
                    authority = _sample_windows_host_offset(samples=samples)
                    offset_seconds = float(authority["offset_seconds"])
            if abs(offset_seconds) * 1000.0 > float(max_offset_ms):
                failures.append(
                    f"WSL host clock offset {offset_seconds * 1000.0:.3f}ms exceeds "
                    f"{float(max_offset_ms):.3f}ms"
                )
        else:
            if repair and (
                chrony.get("leap_status") != "Normal"
                or int(chrony.get("stratum") or 0) <= 0
            ):
                repair_evidence = _attempt_chrony_repair()
                chrony = _chrony_tracking()
                repaired = bool(
                    chrony.get("leap_status") == "Normal"
                    and int(chrony.get("stratum") or 0) > 0
                )
            authority = dict(chrony)
            if authority.get("leap_status") != "Normal":
                failures.append("chrony has no synchronized source")
            if int(authority.get("stratum") or 0) <= 0:
                failures.append("chrony stratum is not selectable")
            offset_seconds = float(authority.get("system_offset_seconds") or 0.0)
            if abs(offset_seconds) * 1000.0 > float(max_offset_ms):
                failures.append(
                    f"chrony system offset {offset_seconds * 1000.0:.3f}ms exceeds "
                    f"{float(max_offset_ms):.3f}ms"
                )
    except Exception as exc:
        failures.append(f"time authority check failed: {type(exc).__name__}: {exc}")

    completed = datetime.now(TAIPEI)
    return {
        "schema_version": 1,
        "status": "ok" if not failures else "failed",
        "ready": not failures,
        "repaired": repaired,
        "repair_evidence": repair_evidence,
        "simulation_schedule_authority": authority,
        "chrony_observation": chrony,
        "max_offset_ms": float(max_offset_ms),
        "max_repair_offset_seconds": float(max_repair_offset_seconds),
        "failures": failures,
        "started_at_taipei": started.isoformat(timespec="milliseconds"),
        "completed_at_taipei": completed.isoformat(timespec="milliseconds"),
    }


def main() -> int:
    args = parse_args()
    if args.max_offset_ms <= 0 or args.max_repair_offset_seconds <= 0:
        raise ValueError("clock thresholds must be positive")
    payload = evaluate_time_sync(
        repair=bool(args.repair),
        max_offset_ms=float(args.max_offset_ms),
        max_repair_offset_seconds=float(args.max_repair_offset_seconds),
        samples=int(args.samples),
    )
    receipt = _repo_path(args.receipt)
    _atomic_json(receipt, payload)
    run_id = datetime.now(TAIPEI).strftime("%Y%m%dT%H%M%S%f")
    _atomic_json(receipt.parent / "runs" / f"{run_id}.json", payload)
    _prune_managed_runs(receipt.parent / "runs")
    print(json.dumps(payload, ensure_ascii=False, sort_keys=True), flush=True)
    return 0 if payload["ready"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
